name: Android CI

on:
  push:
    branches:
      - master
      - feature/*
      - infra/*
  pull_request:
    branches:
      - master
      - infra/*

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      # Define the Java version
      JAVA_VERSION: '17'
      # Define the Android SDK version and build tools
      ANDROID_API_LEVEL: 34
      ANDROID_BUILD_TOOLS_VERSION: '34.0.0'
      # Cache Gradle dependencies
      GRADLE_USER_HOME: ${{ github.workspace }}/.gradle

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
            
      - name: Run unit tests
        run: ./gradlew clean testDebug

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: app/build/reports/tests/testDebugUnitTest/
          
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: ${{ env.ANDROID_API_LEVEL }}
          build-tools: ${{ env.ANDROID_BUILD_TOOLS_VERSION }}
          
      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: TodoList.apk
          path: app/build/outputs/apk/debug/app-debug.apk

